CREATE TABLE POKEMONS 
(
    P_NAME VARCHAR2(100) NOT NULL, 
    POKEMON_NUM NUMBER NOT NULL,
    TYPE_1 VARCHAR2(20) NOT NULL, 
    TYPE_2 VARCHAR2(20), 
    HP NUMBER NOT NULL,
    ATTACK NUMBER NOT NULL, 
    DEFENSE NUMBER NOT NULL, 
    SPEED NUMBER NOT NULL,
    GEN_NUM NUMBER NOT NULL
);

ALTER TABLE POKEMONS  ADD CONSTRAINT name_pk PRIMARY KEY (P_NAME);

CREATE TABLE P_TYPES 
(
    P_TYPE VARCHAR2(20) NOT NULL,
    SUBGROUP VARCHAR2(20) NOT NULL,
    COLOR VARCHAR2(20) NOT NULL
);

ALTER TABLE P_TYPES  ADD CONSTRAINT p_type_pk PRIMARY KEY (P_TYPE);

CREATE TABLE GENERATIONS
(
    GEN_NUM NUMBER NOT NULL,
    MIN_POKEMON_NUM NUMBER NOT NULL,
    MAX_POKEMON_NUM NUMBER NOT NULL,
    YEAR_OF_THE_APPEARANCE NUMBER NOT NULL
);

ALTER TABLE GENERATIONS  ADD CONSTRAINT gen_num_pk PRIMARY KEY (GEN_NUM);

ALTER TABLE POKEMONS
    ADD CONSTRAINT p_type_1_fk FOREIGN KEY (TYPE_1)
        REFERENCES P_TYPES (P_TYPE);
        
ALTER TABLE POKEMONS 
    ADD CONSTRAINT p_type_2_fk FOREIGN KEY (TYPE_2)
        REFERENCES P_TYPES (P_TYPE);
        
ALTER TABLE POKEMONS 
    ADD CONSTRAINT gen_num_fk FOREIGN KEY (GEN_NUM)
        REFERENCES GENERATIONS (GEN_NUM);