--Query 1--

SELECT GEN_NUM,	MAX_POKEMON_NUM - MIN_POKEMON_NUM + 1 AS QUANTITY FROM GENERATIONS

--Query 2--

SELECT P_TYPES.P_TYPE, ROUND(count(*) / (SELECT count(*) FROM POKEMONS ), 4 ) AS PERCENTAGE
FROM P_TYPES
JOIN POKEMONS
ON POKEMONS.TYPE_1 = P_TYPES.P_TYPE
GROUP BY P_TYPE

--Query 3--

SELECT GENERATIONS.GEN_NUM, ROUND(AVG(POKEMONS.ATTACK), 3) AVG_ATTACK
FROM GENERATIONS
JOIN POKEMONS
ON POKEMONS.GEN_NUM = GENERATIONS.GEN_NUM
GROUP BY GENERATIONS.GEN_NUM
ORDER BY GENERATIONS.GEN_NUM ASC
